Projet_API_P_Solution/Projet_API_P_WEB/Models/ErrorViewModel.cs
using System;

namespace Projet_API_P_WEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projet_API_P_Solution/Projet_API_P_WEB/Models/Pays.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projet_API_P_WEB.Models
{
    public class Pays
    {
       
            public int id { get; set; }
            public String nomPays { get; set; }
            public String continent { get; set; }
           

    }
}

Projet_API_P_Solution/Projet_API_P_WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Projet_API_P_WEB.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Projet_API_P_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projet_API_P_Solution/Projet_API_P_WEB/Controllers/PaysController.cs
using Microsoft.AspNetCore.Mvc;
using Projet_API_P_Solution.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projet_API_P_WEB.Controllers
{

    
    public class PaysController : Controller
    {
        public IActionResult CreatePays()
        {
            return View();
        }

        // POST: Pays/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pays pays)
        {
            if (ModelState.IsValid)
            {
                //var URI = API.Instance.AjoutEcurieAsync(pays);
                return RedirectToAction(nameof(Index));
            }
            return View(pays);
        }
    }
}

Projet_API_P_Solution/Projet_API_P_WEB/Views/Pays/CreatePays.cshtml
@model Projet_API_P_Solution.Models.Pays
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pays</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomPays" class="control-label"></label>
                <input asp-for="nomPays" class="form-control" />
                <span asp-validation-for="nomPays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projet_API_P_Solution/Projet_API_P_WEB/Views/Pays/Delete.cshtml
@model Projet_API_P_Solution.Models.Pays

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Etes vous sûre de vouloir effectuer la suppression?</h3>
<div>
    <h4>Pays</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nomPays)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nomPays)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la List</a>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Projet_API_P_Solution/Projet_API_P_WEB/Views/Pays/Edit.cshtml
@model Projet_API_P_Solution.Models.Pays

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pays</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projet_API_P_Solution/Projet_API_P_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projet_API_P_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projet_API_P_WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pays" asp-action="CreatePays">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Projet_API_P_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>